dist: bionic # Ubuntu 18.04

language: generic

cache:
      directories:
      - $HOME/.stack

addons:
      apt:
            sources:
            - sourceline: 'ppa:mati75/ghdl'
            packages:
            - libgmp-dev
            - ghdl

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack install
- stack --no-terminal test --test-arguments "regression" --haddock
