dist: bionic # Ubuntu 18.04

language: generic

cache:
      directories:
      - $HOME/.stack

addons:
      apt:
            packages:
                  - libgmp-dev

before_install:
- travis_retry curl -L http://ghdl.free.fr/site/uploads/Main/ghdl-i686-linux-latest.tar | tar x
- sudo tar -C / -jxvf ghdl*/ghdl*.tar.bz2
- mkdir -p ~/.local/bin
# Doesn't seem to get ghdl into the $PATH.
- export PATH=$HOME/.local/bin:/usr/local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal test --test-arguments "regression --vhdl-checker=\"/usr/local/bin/ghdl -s\"" --haddock
